--insert into profile(name) values('A');
--
--insert into fraction(id, profile_id, month, value) values(1, 1, 1, 0.2);
--insert into fraction(id, profile_id, month, value) values(2, 1, 2, 0.1);
--insert into fraction(id, profile_id, month, value) values(3, 1, 3, 0.0);
--insert into fraction(id, profile_id, month, value) values(4, 1, 4, 0.0);
--insert into fraction(id, profile_id, month, value) values(5, 1, 5, 0.0);
--insert into fraction(id, profile_id, month, value) values(6, 1, 6, 0.0);
--insert into fraction(id, profile_id, month, value) values(7, 1, 7, 0.0);
--insert into fraction(id, profile_id, month, value) values(8, 1, 8, 0.0);
--insert into fraction(id, profile_id, month, value) values(9, 1, 9, 0.0);
--insert into fraction(id, profile_id, month, value) values(10, 1, 10, 0.1);
--insert into fraction(id, profile_id, month, value) values(11, 1, 11, 0.3);
--insert into fraction(id, profile_id, month, value) values(12, 1, 12, 0.3);
--
