version: '3.3'
services:
  energy-consumption-app:
    build:
      context: '.'
    ports:
      - '8080:8080/tcp'
    depends_on:
      - database
    environment:
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/energy-consumption-db'
      - 'SPRING_DATASOURCE_USERNAME=db-default-user'
      - 'SPRING_DATASOURCE_PASSWORD=abc123'
      - 'spring.jpa.hibernate.ddl-auto=create'
      - 'spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true'
      - 'spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect'
      - 'spring.jpa.show-sql=true'
      - 'spring.jpa.properties.hibernate.format_sql=true'
      - 'spring.sql.init.mode=always'
      - 'spring.jpa.defer-datasource-initialization=true'
      - 'logging.level.org.hibernate.SQL=DEBUG'
      - 'logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE'
  database:
    image: 'postgres:15.0'
    environment:
      - 'POSTGRES_DB=energy-consumption-db'
      - 'POSTGRES_USER=db-default-user'
      - 'POSTGRES_PASSWORD=abc123'
    ports:
      - '5432:5432/tcp'